### PR TITLE
Migrate to net standard 1.3 and upgrade test and sample projects to n…

### PR DESCRIPTION
**Pull request by NiklasArbin**
Migrate to net standard 1.3 and upgrade test and sample projects to net core 2 #13

### CODE REVIEW

**Comment by NiklasArbin** [comment]
Still need to fix the CI and set proper nuget versions which I have left out.

**Comment by alexandrnikitin** [comment]
Hi Niklas, 
The PR looks great! I'll review it thoroughly tomorrow.
Thank you for your time and involvement! I appreciate it. 😄

**Comment by alexandrnikitin** [comment]
@NiklasArbin Thank you one more time!

**Comment by NiklasArbin** [comment]
Great! When do you think you'll have time to release a new nuget based on netstandard?

**Comment by alexandrnikitin** [comment]
@NiklasArbin I've just published the next `0.7.0` version targeting .NET Standard 1.3. I'm sorry it took too long; I was too busy at work and almost didn't have free time.

**Pull request merged**
